echo "Hvem er det som tar med lommelykt?"
echo "Hva er klokka om tre timer og fire minutter?"
echo "Liker du suppe med kikerter?"
echo "Hva vil du ha til middag?"
echo "Har du knytta skolissene?"
echo "Kongen har avtalt møte med statsråden klokken ti på halv fem"
echo "Hvor mange meter er det i en nautisk mil?"
echo "Hvem skal vi invitere på bowling?"
echo "Hello world"
echo "Goodbye world"
echo "Det er suppe til middag"

